//TODO1:page_link
//TODO2:campus页面和surrounding页面解决图字不对齐问题:截图当做整体
App({
  globalData: {
    campus:[
      {
      "data_west":[
        [//food
          [//canteen
            {
              latitude:31.837194,
              longtitude:117.258628,
              doors:[],
              name:"芳华餐厅",
              other_name:"芳华食堂",
              img:["https://sbsk.gitee.io/image/test.jpg"],
              page_link:"",
            },
            {
              latitude:31.840690,
              longtitude:117.253785,
              doors:[
                {
                  latitude:31.840685,
                  longtitude:117.253665,
                  name:"西门",
                },
                {
                  latitude:31.840682,
                  longtitude:117.253906,
                  name:"东门",
                },
              ],
              name:"西区学生食堂",
              other_name:"西区学生餐厅",
              img:["https://sd.qunliao.info/fastdfs3/M00/B6/80/ChOxM1xC82CAI3i-AABq8gjkHe8881.png"],
              page_link:["https://sd.qunliao.info/fastdfs4/M00/C8/FF/ChNLklybTdGAZ1ZbAAAat5i0MFQ461.jpg"],
            },
            {
              latitude:31.840485,
              longtitude:117.253780,
              doors:[],
              name:"金桔餐厅",
              other_name:"金桔食堂",
              img:[""],
              page_link:"",
            },
          ],
          [//fruit
            {
              latitude:31.840184,
              longtitude:117.254530,
              doors:[],
              name:"水果",
              other_name:"",
              img:[""],
              page_link:"",
            },
            {
              latitude:31.838406,
              longtitude:117.259575,
              doors:[],
              name:"水果",
              other_name:"",
              img:[""],
              page_link:"",
            },
          ],
          [//food_delivery
            {
              latitude:31.841206,
              longtitude:117.257026,
              doors:[],
              name:"外卖",
              other_name:"",
              img:[""],
              page_link:"",
            },
            {
              latitude:31.838787,
              longtitude:117.259606,
              doors:[],
              name:"外卖",
              other_name:"",
              img:[""],
              page_link:"",
            },
          ],
        ],
        [//study
          [//teaching_building
            {
              latitude:31.838449,
              longtitude:117.255318,
              doors:[],
              name:"三教A楼",
              other_name:"",
              img:[""],
              page_link:"",
            },
            {
              latitude:31.838246,
              longtitude:117.255026,
              doors:[],
              name:"三教B楼",
              other_name:"",
              img:[""],
              page_link:"",
            },
            {
              latitude:31.838028,
              longtitude:117.254451,
              doors:[],
              name:"三教C楼",
              other_name:"",
              img:[""],
              page_link:"",
            },
          ],
          [//library
            {
              latitude:31.839098,
              longtitude:117.257344,
              doors:[],
              name:"西区图书馆",
              other_name:"",
              img:[""],
              page_link:"",
            },
          ],
          [//lab_building
            {
              latitude:31.837496,
              longtitude:117.255969,
              doors:[],
              name:"电一楼",
              other_name:"",
              img:[""],
              page_link:"",
            },
            {
              latitude:31.837672,
              longtitude:117.254896,
              doors:[],
              name:"电四楼",
              other_name:"",
              img:[""],
              page_link:"",
            },         
            {
              latitude:31.837177,
              longtitude:117.256003,
              doors:[],
              name:"电三楼",
              other_name:"",
              img:[""],
              page_link:"",
            },
            {
              latitude:31.837502,
              longtitude:117.256792,
              doors:[],
              name:"电二楼",
              other_name:"",
              img:[""],
              page_link:"",
            },
            {
              latitude:31.838289,
              longtitude:117.256995,
              doors:[],
              name:"力一楼",
              other_name:"",
              img:[""],
              page_link:"",
            },
            {
              latitude:31.837988,
              longtitude:117.257416,
              doors:[],
              name:"力二楼",
              other_name:"",
              img:[""],
              page_link:"",
            },
            {
              latitude:31.838397,
              longtitude:117.258171,
              doors:[],
              name:"力三楼",
              other_name:"",
              img:[""],
              page_link:"",
            },
          ],
        ],
        [//convenience
          [//toilet
            {
              latitude:31.839480,
              longtitude:117.253292,
              doors:[],
              name:"厕所",
              other_name:"卫生间",
              img:[""],
              page_link:"",
            },
            {
              latitude:31.838321,
              longtitude:117.259490,
              doors:[],
              name:"厕所",
              other_name:"卫生间",
              img:[""],
              page_link:"",
            },
          ],
          [//delivery
            {
              latitude:31.837939,
              longtitude:117.259445,
              doors:[],
              name:"小木屋",
              other_name:"快递",
              img:[""],
              page_link:"",
            },
          ],
          [//store
            {
              latitude:31.840884,
              longtitude:117.254561,
              doors:[],
              name:"超市",
              other_name:"小店",
              img:[""],
              page_link:"",
            },
            {
              latitude:31.840642,
              longtitude:117.254851,
              doors:[],
              name:"超市",
              other_name:"小店",
              img:[""],
              page_link:"",
            },
            {
              latitude:31.840151,
              longtitude:117.253276,
              doors:[],
              name:"超市",
              other_name:"小店",
              img:[""],
              page_link:"",
            },
            {
              latitude:31.839973,
              longtitude:117.254523,
              doors:[],
              name:"超市",
              other_name:"小店",
              img:[""],
              page_link:"",
            },
            {
              latitude:31.838367,
              longtitude:117.259462,
              doors:[],
              name:"超市",
              other_name:"小店",
              img:[""],
              page_link:"",
            },
          ],
          [//printing
            {
              latitude:31.840658,
              longtitude:117.255476,
              doors:[],
              name:"文印",
              other_name:"",
              img:[""],
              page_link:"",
            },
          ],
        ],
        [//traffic
          [//gate
            {
              latitude:31.841225,
              longtitude:117.256759,
              doors:[],
              name:"西区北门",
              other_name:"",
              img:[""],
              page_link:"",
            },
            {
              latitude:31.838758,
              longtitude:117.259700,
              doors:[],
              name:"西区东门",
              other_name:"",
              img:[""],
              page_link:"",
            },
          ],
          [//bicycle
          ],
          [//bus
            {
              latitude:31.838828,
              longtitude:117.256579,
              doors:[],
              name:"西区公交站",
              other_name:"",
              img:[""],
              page_link:"",
            },
          ],
        ],
        [//sports
          [//sports
            {
              latitude:31.839356,
              longtitude:117.252996,
              doors:[],
              name:"西区操场",
              other_name:"",
              img:[""],
              page_link:"",
            },
            {
              latitude:31.839488,
              longtitude:117.253480,
              doors:[],
              name:"乒乓球馆",
              other_name:"",
              img:[""],
              page_link:"",
            },
          ],
        ],
        [//scenery
          [//scenery
            {
              latitude:31.837867,
              longtitude:117.255564,
              doors:[],
              name:"严济慈广场",
              other_name:"",
              img:[""],
              page_link:"",
            },
          ],
        ],
        [//dormitory
          [//dormitory
            {
              latitude:31.841023,
              longtitude:117.255007,
              doors:[],
              name:"学生公寓1号楼",
              other_name:"",
              img:[""],
              page_link:"",
            },
            {
              latitude:31.840683,
              longtitude:117.255001,
              doors:[],
              name:"学生公寓2号楼",
              other_name:"",
              img:[""],
              page_link:"",
            },
            {
              latitude:31.840292,
              longtitude:117.254863,
              doors:[],
              name:"学生公寓3号楼",
              other_name:"",
              img:[""],
              page_link:"",
            },
            {
              latitude:31.840401,
              longtitude:117.255449,
              doors:[],
              name:"学生公寓6号楼",
              other_name:"",
              img:[""],
              page_link:"",
            },
            {
              latitude:31.840104,
              longtitude:117.253974,
              doors:[],
              name:"学生公寓4号楼",
              other_name:"",
              img:[""],
              page_link:"",
            },
            {
              latitude:31.839742,
              longtitude:117.254177,
              doors:[],
              name:"学生公寓5号楼",
              other_name:"",
              img:[""],
              page_link:"",
            },
            {
              latitude:31.838515,
              longtitude:117.259134,
              doors:[],
              name:"1幢宿舍",
              other_name:"",
              img:[""],
              page_link:"",
            },
            {
              latitude:31.838245,
              longtitude:117.259023,
              doors:[],
              name:"2幢宿舍",
              other_name:"",
              img:[""],
              page_link:"",
            },
            {
              latitude:31.837958,
              longtitude:117.258984,
              doors:[],
              name:"3幢宿舍",
              other_name:"",
              img:[""],
              page_link:"",
            },
            {
              latitude:31.837682,
              longtitude:117.258947,
              doors:[],
              name:"4幢宿舍",
              other_name:"",
              img:[""],
              page_link:"",
            },
            {
              latitude:31.837471,
              longtitude:117.258906,
              doors:[],
              name:"5幢宿舍",
              other_name:"",
              img:[""],
              page_link:"",
            },
            {
              latitude:31.836707,
              longtitude:117.258753,
              doors:[],
              name:"学生公寓11号楼",
              other_name:"",
              img:[""],
              page_link:"",
            },
            {
              latitude:31.836361,
              longtitude:117.258691,
              doors:[],
              name:"学生公寓10号楼",
              other_name:"",
              img:[""],
              page_link:"",
            },
            {
              latitude:31.835979,
              longtitude:117.258609,
              doors:[],
              name:"学生公寓9号楼",
              other_name:"",
              img:[""],
              page_link:"",
            },
            {
              latitude:31.835620,
              longtitude:117.258266,
              doors:[],
              name:"学生公寓8号楼",
              other_name:"",
              img:[""],
              page_link:"",
            },
            {
              latitude:31.835193,
              longtitude:117.258197,
              doors:[],
              name:"学生公寓7号楼",
              other_name:"",
              img:[""],
              page_link:"",
            },
          ],
        ],
        [//hospital
          [//hospital
          ],
        ],
      ],
      "data_mid":[
        [//food
          [//canteen

          ],
          [//fruit

          ],
          [//food_delivery

          ],
        ],
        [//study
          [//teaching_building

          ],
          [//library

          ],
          [//lab_building

          ],
        ],
        [//convenience
          [//toilet

          ],
          [//delivery
          
          ],
          [//store

          ],
          [//printing

          ],
        ],
        [//traffic
          [//gate

          ],
          [//bicycle

          ],
          [//bus

          ],
        ],
        [//sports
          [//sports

          ],
        ],
        [//scenery
          [//scenery

          ],
        ],
        [//dormitory
          [//dormitory

          ],
        ],
        [//hospital
          [//hospital

          ],
        ],
      ],
      "data_east":[
        [//food
          [//canteen

          ],
          [//fruit

          ],
          [//food_delivery

          ],
        ],
        [//study
          [//teaching_building

          ],
          [//library

          ],
          [//lab_building

          ],
        ],
        [//convenience
          [//toilet

          ],
          [//delivery
          
          ],
          [//store

          ],
          [//printing

          ],
        ],
        [//traffic
          [//gate

          ],
          [//bicycle

          ],
          [//bus

          ],
        ],
        [//sports
          [//sports

          ],
        ],
        [//scenery
          [//scenery

          ],
        ],
        [//dormitory
          [//dormitory

          ],
        ],
        [//hospital
          [//hospital

          ],
        ],
      ],
      "data_gaoxin":[
        [//food
          [//canteen

          ],
          [//fruit

          ],
          [//food_delivery

          ],
        ],
        [//study
          [//teaching_building

          ],
          [//library

          ],
          [//lab_building

          ],
        ],
        [//convenience
          [//toilet

          ],
          [//delivery
          
          ],
          [//store

          ],
          [//printing

          ],
        ],
        [//traffic
          [//gate

          ],
          [//bicycle

          ],
          [//bus

          ],
        ],
        [//sports
          [//sports

          ],
        ],
        [//scenery
          [//scenery

          ],
        ],
        [//dormitory
          [//dormitory

          ],
        ],
        [//hospital
          [//hospital

          ],
        ],
      ],
      }
    ],
    surroundings:[
      [//clothes
        {},
      ],
      [//restaurant
        {
          latitude:31.840509,
          longtitude:117.260186,
          name:"无锡汤包",
          img:[""],
          intro:"",
        },
        {
          latitude:31.837881,
          longtitude:117.265668,
          name:"汉堡王",
          img:["/images/icon1.png"],
          intro:"",
        },
      ],
      [//sports
        {},
      ],
      [//fruit
        {
          latitude:31.840049,
          longtitude:117.260226,
          name:"鲜丰",
          img:[""],
          intro:"",
        },
      ],
      [//tea_coffee
        {
          latitude:31.840163,
          longtitude:117.260169,
          name:"蜜雪冰城",
          img:[""],
          intro:"",
        },
        {
          latitude:31.840779,
          longtitude:117.260111,
          name:"巴莉甜甜",
          img:[""],
          intro:"",
        },
      ],
      [//store
        {
          latitude:31.839635,
          longtitude:117.260180,
          name:"百分百超市",
          img:[""],
          intro:"",
        },
        {
          latitude:31.839421,
          longtitude:117.260219,
          name:"罗森",
          img:[""],
          intro:"",
        },
        {
          latitude:31.839516,
          longtitude:117.260178,
          name:"桂太太生活超市",
          img:[""],
          intro:"",
        },
      ],
      [//drug_store
        {
          latitude:31.843316,
          longtitude:117.259739,
          name:"百姓缘大药房",
          img:[""],
          intro:"",
        },
      ],
      [//haircut
        {
          latitude:31.840893,
          longtitude:117.260113,
          name:"理发",
          img:[""],
          intro:"",
        },
      ],
      [//bank
        {},
      ],
      [//mobile_store
        {},
      ],
      [//delivery
        {
          latitude:31.839493,
          longtitude:117.260178,
          name:"桂太太快递收取点",
          img:[""],
          intro:"",
        },
      ],
      [//hotel
        {
          latitude:31.841258,
          longtitude:117.261037,
          name:"7+1商务酒店",
          img:[""],
          intro:"",
        },
        {
          latitude:31.833538,
          longtitude:117.264556,
          name:"一路同行精选酒店",
          img:[""],
          intro:"",
        },
      ],
      [//bicycle
        {},
      ],
      [//shared_ebike
        {
          latitude:31.841606,
          longtitude:117.256815,
          name:"还车点",
          img:[""],
          intro:"",
        },
        {
          latitude:31.837182,
          longtitude:117.265661,
          name:"还车点",
          img:[""],
          intro:"",
        },
      ],
      [//traffic(including subway,bus,gaotie,airport)
        {
          latitude:31.841638,
          longtitude:117.273107,
          name:"地铁站-中国科大东区",
          img:[""],
          intro:"",
        },
        {
          latitude:31.854538,
          longtitude:117.255585,
          name:"地铁站-三里庵",
          img:[""],
          intro:"",
        },
        {
          latitude:31.841389,
          longtitude:117.250157,
          name:"公交站",
          img:[""],
          intro:"",
        },
        {
          latitude:31.839380,
          longtitude:117.251619,
          name:"公交站",
          img:[""],
          intro:"",
        },
        {
          latitude:31.841299,
          longtitude:117.253029,
          name:"公交站",
          img:[""],
          intro:"",
        },
        {
          latitude:31.798961,
          longtitude:117.290199,
          name:"高铁站-合肥南站",
          img:[""],
          intro:"",
        },
        {
          latitude:31.886239,
          longtitude:117.317274,
          name:"高铁站-合肥站",
          img:[""],
          intro:"",
        },
        {
          latitude:31.985274,
          longtitude:116.977942,
          name:"合肥新桥国际机场",
          img:[""],
          intro:"",
        },
      ],
      [//hospital
        {
          latitude:31.844043,
          longtitude:117.260109,
          name:"安徽省胸科医院",
          img:[""],
          intro:"",
        },
        {
          latitude:31.850269,
          longtitude:117.265669,
          name:"安徽医科大学附属口腔医院",
          img:[""],
          intro:"",
        },
        {
          latitude:31.850205,
          longtitude:117.265933,
          name:"安医大第一附属医院",
          img:[""],
          intro:"",
        },
        {
          latitude:31.852529,
          longtitude:117.258978,
          name:"安徽省中医院",
          img:[""],
          intro:"",
        },
      ],
      [//mall
        {
          latitude:31.853287,
          longtitude:117.256390,
          name:"国购广场",
          img:[""],
          intro:"",
        },
        {
          latitude:31.853872,
          longtitude:117.257412,
          name:"之心城",
          img:[""],
          intro:"",
        },
      ],
      [//scenery
        {},
      ],
      [//cinema
        {},
      ],
      [//glasses
        {
          latitude:31.842137,
          longtitude:117.259722,
          name:"精功眼镜",
          img:[""],
          intro:"",
        },
        {
          latitude:31.832619,
          longtitude:117.266606,
          name:"中科眼镜",
          img:[""],
          intro:"",
        },
      ],
      [//other
        {
          latitude:31.837050,
          longtitude:117.264038,
          name:"知行书店",
          img:[""],
          intro:"",
        },
      ],
    ]
  },
  onLaunch() {
  },
})